name: "Terraform-Apply-Infra-Release"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:	
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: 'us-west-2'
    steps:
      - uses: actions/checkout@v2
 
      - name: Deploy cloudformation
        run: |
          aws cloudformation create-stack --stack-name vpcstack --template-body file://template.yml
